### ISSUE TITLE
Create a my-nav component

### ISSUE THREAD

**Issue by web-dave** [web-dave/angular_workshop#2]
1. Open a new Terminal 
2. run `ng g c my-nav` to generate a Navigation Component
3. Add HTML to your Nav Component
<details>
  <summary>my-nav.component.html</summary>

```html
<header>
  <nav>
    <div id="brand">
      <div id="logo"></div>
    </div>
    <div id="menu">
      <div id="menu-toggle">
        <!-- class="closeMenu" -->
        <div id="menu-icon">
          <div class="bar"></div>
          <div class="bar"></div>
          <div class="bar"></div>
        </div>
      </div>
      <ul>
        <!-- class="showMenu" -->
        <li><a href="#books">Books</a></li>
        <li><a href="#about">About</a></li>
      </ul>
    </div>
  </nav>
</header>
   ```
 </details>
4. Add SCSS helper
<details>
  <summary>src/_utils.scss</summary>

```scss
/*** Mixins ***/

@mixin object($width, $height, $bg) {
  width: $width;
  height: $height;
  background: $bg;
}
@mixin transPos($top, $right, $bottom, $left, $transX, $transY) {
  position: absolute;
  top: $top;
  left: $left;
  right: $right;
  bottom: $bottom;
  transform: translate($transX, $transY);
}

/*** Centering Hack ***/
@mixin center {
  display: flex;
  justify-content: center;
  align-items: center;
}

/*** Color Variables ***/
$bg: #5661f2;
$nav-bg: #46b2f0;
$pink: #fa6c98;
$aqua: #79edfc;
$accent: #fff;

```
</details>
5. Add SCSS to your Nav Component
<details>
  <summary>my-nav.component.scss</summary>

```scss
@use "sass:color";
@use "../../utils";

/*** Header Styles ***/
header {
  @include utils.object(100vw, 160px, utils.$bg);
  display: flex;
}

/*** Navigation Styles ***/
nav {
  @include utils.object(100vw, 160px, utils.$nav-bg);
  display: grid;
  grid-template-columns: 1fr 1fr;
  position: fixed;
  left: 0;
  top: 0;
  z-index: 10;
  transition: all 0.3s;
  &.navShadow {
    box-shadow: 0 4px 30px -5px rgba(#000, 0.2);
    height: 100px;
    #word-mark {
      opacity: 0;
    }
  }
}

#brand,
#menu,
ul {
  display: flex;
  align-items: center;
}

#brand {
  padding-left: 40px;
}

#logo {
  @include utils.object(55px, 55px, utils.$accent);
  border-radius: 50%;
  cursor: pointer;
}

/*** Menu Styles ***/
#menu {
  justify-content: flex-end;
  padding-right: 40px;
}

li {
  margin-left: 20px;
  list-style: none;
  a {
    @include utils.object(80px, 20px, utils.$accent);
    display: block;
    border-radius: 90px;
    text-align: center;

    &.active {
      background-color: hotpink;
    }
  }
}

#menu-toggle {
  @include utils.object(
    55px,
    55px,
    color.adjust(utils.$nav-bg, $lightness: -5%)
  );
  @include utils.center;
  border-radius: 50%;
  cursor: pointer;
  display: none;
  &:hover .bar {
    width: 25px;
  }
  &.closeMenu {
    .bar {
      width: 25px;
      &:first-child {
        transform: translateY(7px) rotate(45deg);
      }
      &:nth-child(2) {
        transform: scale(0);
      }
      &:last-child {
        transform: translateY(-7px) rotate(-45deg);
      }
    }
  }
}

.bar {
  @include utils.object(25px, 2px, utils.$accent);
  transition: 0.3s ease-in-out;
  &:nth-child(2) {
    width: 20px;
    margin: 5px 0;
  }
  &:last-child {
    width: 15px;
  }
}

/*** Hero Section Styles ***/
#hero-section {
  @include utils.object(100vw, calc(100vh - 160px), null);
  @include utils.center;
  margin-top: 160px;
}

#head-line {
  @include utils.object(520px, 30px, utils.$accent);
  border-radius: 90px;
  position: relative;
  &:before,
  &:after {
    content: "";
    height: 30px;
    border-radius: 90px;
  }
  &:before {
    @include utils.object(360px, null, utils.$accent);
    @include utils.transPos(-60px, null, null, 50%, -50%, 0);
  }
  &:after {
    @include utils.object(200px, null, utils.$accent);
    @include utils.transPos(null, null, -60px, 50%, -50%, 0);
  }
}

/*** Section Styles ***/
section {
  @include utils.object(100vw, calc(100vh - 100px), null);
  display: flex;
  justify-content: center;
  &:nth-child(odd) {
    background: utils.$pink;
  }
  &:nth-child(even) {
    background: utils.$aqua;
  }
}

#heading {
  @include utils.object(120px, 20px, utils.$accent);
  border-radius: 90px;
  margin-top: 40px;
}

/*** Responsive Menu For Smaller Device ***/

@media screen and (max-width: 767px) {
  #menu-toggle {
    display: flex;
  }
  ul {
    display: inline-block;
    @include utils.object(100vw, 0, utils.$aqua);
    @include utils.transPos(160px, null, null, null, null, null);
    box-shadow: 0 5px 30px -4px rgba(#000, 0.2);
    transition: all 0.3s;
    &.showMenu {
      height: 250px;
      li {
        height: 80px;
        opacity: 1;
        visibility: visible;
      }
    }
  }
  li {
    @include utils.object(50%, 80px, null);
    float: left;
    padding-left: 40px;
    opacity: 0;
    visibility: hidden;
    margin-left: 0;
    transition: all 0.3s 0.1s;
    &:first-child,
    &:nth-child(2) {
      margin-top: 80px;
    }
  }
  #head-line {
    transform: scale(0.8);
  }
}
```
</details>
6. Import Your Nav Component into the AppComonent
<details>
<summary>app.component.ts</summary>

```ts
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, MyNavComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
  title = 'angular-workshop';
}
```
</details>
7. Add global styling
<details>
<summary>styles.scss</summary>

```scss
@use "./utils";

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  background-color: utils.$bg;
  overflow-x: hidden;
  overflow-y: scroll;
}
```
</details>
8. Use Your Nav Component in the template of the AppComponent 
<details>
<summary>app.component.html</summary>

```html
<app-my-nav />
```
</details>
