### ISSUE TITLE
Use the Service

### ISSUE THREAD

**Issue by web-dave** [web-dave/angular_workshop#7]
1. Get BookService into `BookList` via DI
<details>
<summary>book-list.component.ts</summary>

```ts
 service = inject(BookService);
```
</details>

2. Get All Books 
<details>
<summary>book-list.component.ts</summary>

```ts
 ...
  books: any[] = [];
  getAllBooks() {
    this.service.getAll().subscribe((data) => (this.books = data));
  }
```
</details>
3. Show all Books
<details>
<summary>book-list.component.html</summary>

```html
 ...
@for (book of books; track $index) {
<div class="book">
  <strong>{{ book.title }}</strong> <br />
  <small>{{ book.subtitle }}</small>
</div>
}
```
</details>

4.  Styling
<details>
<summary>book-list.component.scss</summary>

```css
@use "../../../utils";

.book {
  @include utils.object(100%, 60px, utils.$aqua);
  border-radius: 90px;
  margin-top: 10px;
  padding-left: 45px;
  padding-top: 10px;
}
```
</details>
