### ISSUE TITLE
Book Preview

### ISSUE THREAD

**Issue by web-dave** [web-dave/angular_workshop#8]
1. Generate `BookPreview` Component
`ng g c books/book-preview`
2. declair a `Input` and a `Output`
<details>
<summary>book-preview.component.ts</summary>

```ts
export class BookPreviewComponent {
  @Input() book: any;
  @Output() bookSelected = new EventEmitter();
}
```
</details>
2. show title and Subtitle in template
<details>
<summary>book-preview.component.html</summary>

```html
<strong>{{ book.title }}</strong> <br />
<small>{{ book.subtitle }}</small>
```
</details>
<details>
<summary>book-preview.component.scss</summary>

```scss
@use "../../../utils";
:host {
  display: block;
  @include utils.object(100%, 60px, utils.$aqua);
  border-radius: 90px;
  margin-top: 10px;
  padding-left: 45px;
  padding-top: 10px;
}
```
</details>
3. use `book-preview` in book-list template
<details>
<summary>book-list.component.html</summary>

```html
@for (book of books; track $index) {
  <app-book-preview [book]="book" />
}
```
</details>
4. click on a button should emit a event with the Book from `book-preview` to `book-list`
<details>
<summary>book-preview.component.ts</summary>

```ts
  showMore() {
    this.bookSelected.emit(this.book);
  }
```
</details>

<details>
<summary>book-preview.component.html</summary>

```html
<button (click)="showMore()">details</button>
```
</details>

<details>
<summary>book-list.component.ts</summary>

```ts
selectBook(e: any) {
    console.log(e);
  }
```
</details>

<details>
<summary>book-list.component.html</summary>

```html
<app-book-preview [book]="book" (bookSelected)="selectBook($event)" />
```
</details>
